insert into room_type (id, type) values (1, 'science fiction');
insert into room_type (id, type) values (2, 'biography');
insert into room_type (id, type) values (3, 'self-help');
insert into room_type (id, type) values (4, 'fantasy');
insert into room_type (id, type) values (5, 'non-fiction');
insert into room_type (id, type) values (6, 'non-fiction');
insert into room_type (id, type) values (7, 'non-fiction');
insert into room_type (id, type) values (8, 'fiction');
insert into room_type (id, type) values (9, 'mystery');
insert into room_type (id, type) values (10, 'fantasy');
insert into room_type (id, type) values (11, 'historical fiction');
insert into room_type (id, type) values (12, 'historical fiction');
insert into room_type (id, type) values (13, 'fantasy');
insert into room_type (id, type) values (14, 'science fiction');
insert into room_type (id, type) values (15, 'mystery');
insert into room_type (id, type) values (16, 'self-help');
insert into room_type (id, type) values (17, 'historical fiction');
insert into room_type (id, type) values (18, 'self-help');
insert into room_type (id, type) values (19, 'biography');
insert into room_type (id, type) values (20, 'fantasy');
insert into room_type (id, type) values (21, 'non-fiction');
insert into room_type (id, type) values (22, 'fiction');
insert into room_type (id, type) values (23, 'science fiction');
insert into room_type (id, type) values (24, 'fiction');
insert into room_type (id, type) values (25, 'biography');
insert into room_type (id, type) values (26, 'non-fiction');
insert into room_type (id, type) values (27, 'fiction');
insert into room_type (id, type) values (28, 'non-fiction');
insert into room_type (id, type) values (29, 'non-fiction');
insert into room_type (id, type) values (30, 'self-help');
insert into room_type (id, type) values (31, 'fantasy');
insert into room_type (id, type) values (32, 'non-fiction');
insert into room_type (id, type) values (33, 'self-help');
insert into room_type (id, type) values (34, 'fantasy');
insert into room_type (id, type) values (35, 'mystery');
insert into room_type (id, type) values (36, 'historical fiction');
insert into room_type (id, type) values (37, 'fantasy');
insert into room_type (id, type) values (38, 'mystery');
insert into room_type (id, type) values (39, 'thriller');
insert into room_type (id, type) values (40, 'non-fiction');
insert into room_type (id, type) values (41, 'romance');
insert into room_type (id, type) values (42, 'self-help');
insert into room_type (id, type) values (43, 'science fiction');
insert into room_type (id, type) values (44, 'biography');
insert into room_type (id, type) values (45, 'romance');
insert into room_type (id, type) values (46, 'romance');
insert into room_type (id, type) values (47, 'thriller');
insert into room_type (id, type) values (48, 'science fiction');
insert into room_type (id, type) values (49, 'thriller');
insert into room_type (id, type) values (50, 'historical fiction');
