<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230801111831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE bookmark DROP CONSTRAINT bookmark_user_id_fkey');
        $this->addSql('ALTER TABLE bookmark ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bookmark ALTER user_id_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bookmark ADD CONSTRAINT FK_DA62921D9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_hotel_feedback DROP CONSTRAINT give_hotel_feedback_user_id_fkey');
        $this->addSql('ALTER TABLE give_hotel_feedback DROP CONSTRAINT give_hotel_feedback_hotel_id_fkey');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER user_id_id DROP NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER hotel_id DROP NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER date_feedback DROP DEFAULT');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER date_feedback SET NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ADD CONSTRAINT FK_FF08E90D9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_hotel_feedback ADD CONSTRAINT FK_FF08E90D3243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_room_feedback DROP CONSTRAINT give_room_feedback_user_id_fkey');
        $this->addSql('ALTER TABLE give_room_feedback DROP CONSTRAINT give_room_feedback_room_id_fkey');
        $this->addSql('ALTER TABLE give_room_feedback ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE give_room_feedback ALTER user_id_id DROP NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ALTER room_id DROP NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ALTER date_feedback DROP DEFAULT');
        $this->addSql('ALTER TABLE give_room_feedback ALTER date_feedback SET NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ADD CONSTRAINT FK_82C7424A9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_room_feedback ADD CONSTRAINT FK_82C7424A54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE hotel ALTER phone_number TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE hotel_media DROP CONSTRAINT have_media_media_id_fkey');
        $this->addSql('ALTER TABLE hotel_media DROP CONSTRAINT have_media_hotel_id_fkey');
        $this->addSql('ALTER TABLE hotel_media DROP CONSTRAINT hotel_media_pkey');
        $this->addSql('ALTER TABLE hotel_media DROP id');
        $this->addSql('ALTER TABLE hotel_media ADD CONSTRAINT FK_89F86FC83243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_media ADD CONSTRAINT FK_89F86FC8EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_media ADD PRIMARY KEY (hotel_id, media_id)');
        $this->addSql('ALTER TABLE hotel_promotion DROP CONSTRAINT have_promotion_promotion_id_fkey');
        $this->addSql('ALTER TABLE hotel_promotion DROP CONSTRAINT have_promotion_hotel_id_fkey');
        $this->addSql('ALTER TABLE hotel_promotion DROP CONSTRAINT hotel_promotion_pkey');
        $this->addSql('ALTER TABLE hotel_promotion DROP id');
        $this->addSql('ALTER TABLE hotel_promotion ADD CONSTRAINT FK_7F540C133243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_promotion ADD CONSTRAINT FK_7F540C13139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_promotion ADD PRIMARY KEY (hotel_id, promotion_id)');
        $this->addSql('ALTER TABLE hotel_partnership DROP CONSTRAINT have_proposition_partnership_id_fkey');
        $this->addSql('ALTER TABLE hotel_partnership DROP CONSTRAINT have_proposition_hotel_id_fkey');
        $this->addSql('ALTER TABLE hotel_partnership DROP CONSTRAINT hotel_partnership_pkey');
        $this->addSql('ALTER TABLE hotel_partnership DROP id');
        $this->addSql('ALTER TABLE hotel_partnership ADD CONSTRAINT FK_58D79C813243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_partnership ADD CONSTRAINT FK_58D79C816AE7F85 FOREIGN KEY (partnership_id) REFERENCES partnership (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_partnership ADD PRIMARY KEY (hotel_id, partnership_id)');
        $this->addSql('ALTER TABLE media ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE partnership ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE partnership ALTER date_proposition DROP DEFAULT');
        $this->addSql('ALTER TABLE partnership ALTER date_proposition SET NOT NULL');
        $this->addSql('ALTER TABLE partnership ALTER partnership_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE partnership ALTER is_accepted DROP DEFAULT');
        $this->addSql('ALTER TABLE partnership_user DROP CONSTRAINT propose_partnership_id_fkey');
        $this->addSql('ALTER TABLE partnership_user DROP CONSTRAINT propose_user_id_fkey');
        $this->addSql('ALTER TABLE partnership_user DROP CONSTRAINT partnership_user_pkey');
        $this->addSql('ALTER TABLE partnership_user DROP id');
        $this->addSql('ALTER TABLE partnership_user ADD CONSTRAINT FK_62B0C6D26AE7F85 FOREIGN KEY (partnership_id) REFERENCES partnership (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partnership_user ADD CONSTRAINT FK_62B0C6D2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partnership_user ADD PRIMARY KEY (partnership_id, user_id)');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT payment_reservation_id_fkey');
        $this->addSql('ALTER TABLE payment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE payment ALTER reservation_id DROP NOT NULL');
        $this->addSql('ALTER TABLE payment ALTER date_payment DROP DEFAULT');
        $this->addSql('ALTER TABLE payment ALTER method_payment TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promotion ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE promotion ALTER start_date DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT reservation_user_id_fkey');
        $this->addSql('ALTER TABLE reservation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER user_id_id DROP NOT NULL');
        $this->addSql('ALTER TABLE reservation ALTER date_reservation DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ALTER date_reservation SET NOT NULL');
        $this->addSql('ALTER TABLE reservation ALTER is_annulled DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849559D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_contain DROP CONSTRAINT reservation_contain_room_id_fkey');
        $this->addSql('ALTER TABLE reservation_contain DROP CONSTRAINT reservation_contain_reservation_id_fkey');
        $this->addSql('ALTER TABLE reservation_contain ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservation_contain ALTER room_id DROP NOT NULL');
        $this->addSql('ALTER TABLE reservation_contain ALTER reservation_id DROP NOT NULL');
        $this->addSql('ALTER TABLE reservation_contain ADD CONSTRAINT FK_2C7A4C4D54177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_contain ADD CONSTRAINT FK_2C7A4C4DB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resto DROP CONSTRAINT resto_hotel_id_fkey');
        $this->addSql('DROP INDEX IDX_892155B13243BB18');
        $this->addSql('ALTER TABLE resto ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE resto ALTER hotel_id DROP NOT NULL');
        $this->addSql('ALTER TABLE resto ALTER resto_url_img TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE resto ADD CONSTRAINT FK_892155B13243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_892155B13243BB18 ON resto (hotel_id)');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT room_hotel_id_fkey');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT room_room_type_id_fkey');
        $this->addSql('ALTER TABLE room ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE room ALTER hotel_id DROP NOT NULL');
        $this->addSql('ALTER TABLE room ALTER room_type_id DROP NOT NULL');
        $this->addSql('ALTER TABLE room ALTER room_category TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE room ALTER room_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE room ALTER room_url_img TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B3243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B296E3073 FOREIGN KEY (room_type_id) REFERENCES room_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_room_content DROP CONSTRAINT room_contain_room_id_fkey');
        $this->addSql('ALTER TABLE room_room_content DROP CONSTRAINT room_contain_room_content_id_fkey');
        $this->addSql('ALTER TABLE room_room_content DROP CONSTRAINT room_room_content_pkey');
        $this->addSql('ALTER TABLE room_room_content DROP id');
        $this->addSql('ALTER TABLE room_room_content ADD CONSTRAINT FK_A49594DA54177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_room_content ADD CONSTRAINT FK_A49594DAB052D3F1 FOREIGN KEY (room_content_id) REFERENCES room_content (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_room_content ADD PRIMARY KEY (room_id, room_content_id)');
        $this->addSql('ALTER TABLE room_bookmark DROP CONSTRAINT bookmark_contain_bookmark_id_fkey');
        $this->addSql('ALTER TABLE room_bookmark DROP CONSTRAINT bookmark_contain_room_id_fkey');
        $this->addSql('ALTER TABLE room_bookmark DROP CONSTRAINT room_bookmark_pkey');
        $this->addSql('ALTER TABLE room_bookmark DROP id');
        $this->addSql('ALTER TABLE room_bookmark ADD CONSTRAINT FK_7A8452D954177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_bookmark ADD CONSTRAINT FK_7A8452D992741D25 FOREIGN KEY (bookmark_id) REFERENCES bookmark (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_bookmark ADD PRIMARY KEY (room_id, bookmark_id)');
        $this->addSql('ALTER TABLE room_content ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE room_content ALTER content_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE room_content ALTER content_url_img TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE room_type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE room_type ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT user_user_type_id_fkey');
        $this->addSql('DROP INDEX user_email_key');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER user_type_id DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER gender TYPE VARCHAR(1)');
        $this->addSql('ALTER TABLE "user" ALTER phone_number DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER phone_number TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" ALTER profil_url_img TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN birthdate TO start_date');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6499D419299 FOREIGN KEY (user_type_id) REFERENCES user_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_type ALTER user_type TYPE VARCHAR(255)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6499D419299');
        $this->addSql('CREATE SEQUENCE user_id_seq');
        $this->addSql('SELECT setval(\'user_id_seq\', (SELECT MAX(id) FROM "user"))');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\')');
        $this->addSql('ALTER TABLE "user" ALTER user_type_id SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER gender TYPE CHAR(1)');
        $this->addSql('ALTER TABLE "user" ALTER phone_number SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER phone_number TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE "user" ALTER profil_url_img TYPE TEXT');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN start_date TO birthdate');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT user_user_type_id_fkey FOREIGN KEY (user_type_id) REFERENCES user_type (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX user_email_key ON "user" (email)');
        $this->addSql('CREATE SEQUENCE hotel_id_seq');
        $this->addSql('SELECT setval(\'hotel_id_seq\', (SELECT MAX(id) FROM hotel))');
        $this->addSql('ALTER TABLE hotel ALTER id SET DEFAULT nextval(\'hotel_id_seq\')');
        $this->addSql('ALTER TABLE hotel ALTER phone_number TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE reservation_contain DROP CONSTRAINT FK_2C7A4C4D54177093');
        $this->addSql('ALTER TABLE reservation_contain DROP CONSTRAINT FK_2C7A4C4DB83297E7');
        $this->addSql('CREATE SEQUENCE reservation_contain_id_seq');
        $this->addSql('SELECT setval(\'reservation_contain_id_seq\', (SELECT MAX(id) FROM reservation_contain))');
        $this->addSql('ALTER TABLE reservation_contain ALTER id SET DEFAULT nextval(\'reservation_contain_id_seq\')');
        $this->addSql('ALTER TABLE reservation_contain ALTER room_id SET NOT NULL');
        $this->addSql('ALTER TABLE reservation_contain ALTER reservation_id SET NOT NULL');
        $this->addSql('ALTER TABLE reservation_contain ADD CONSTRAINT reservation_contain_room_id_fkey FOREIGN KEY (room_id) REFERENCES room (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_contain ADD CONSTRAINT reservation_contain_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE room_type_id_seq');
        $this->addSql('SELECT setval(\'room_type_id_seq\', (SELECT MAX(id) FROM room_type))');
        $this->addSql('ALTER TABLE room_type ALTER id SET DEFAULT nextval(\'room_type_id_seq\')');
        $this->addSql('ALTER TABLE room_type ALTER type TYPE VARCHAR(100)');
        $this->addSql('CREATE SEQUENCE room_content_id_seq');
        $this->addSql('SELECT setval(\'room_content_id_seq\', (SELECT MAX(id) FROM room_content))');
        $this->addSql('ALTER TABLE room_content ALTER id SET DEFAULT nextval(\'room_content_id_seq\')');
        $this->addSql('ALTER TABLE room_content ALTER content_name TYPE VARCHAR(150)');
        $this->addSql('ALTER TABLE room_content ALTER content_url_img TYPE TEXT');
        $this->addSql('ALTER TABLE hotel_media DROP CONSTRAINT FK_89F86FC83243BB18');
        $this->addSql('ALTER TABLE hotel_media DROP CONSTRAINT FK_89F86FC8EA9FDD75');
        $this->addSql('DROP INDEX have_media_pkey');
        $this->addSql('ALTER TABLE hotel_media ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE hotel_media ADD CONSTRAINT have_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_media ADD CONSTRAINT have_media_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_media ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE hotel_promotion DROP CONSTRAINT FK_7F540C133243BB18');
        $this->addSql('ALTER TABLE hotel_promotion DROP CONSTRAINT FK_7F540C13139DF194');
        $this->addSql('DROP INDEX have_promotion_pkey');
        $this->addSql('ALTER TABLE hotel_promotion ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE hotel_promotion ADD CONSTRAINT have_promotion_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES promotion (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_promotion ADD CONSTRAINT have_promotion_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_promotion ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE promotion_id_seq');
        $this->addSql('SELECT setval(\'promotion_id_seq\', (SELECT MAX(id) FROM promotion))');
        $this->addSql('ALTER TABLE promotion ALTER id SET DEFAULT nextval(\'promotion_id_seq\')');
        $this->addSql('ALTER TABLE promotion ALTER start_date SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE give_room_feedback DROP CONSTRAINT FK_82C7424A9D86650F');
        $this->addSql('ALTER TABLE give_room_feedback DROP CONSTRAINT FK_82C7424A54177093');
        $this->addSql('CREATE SEQUENCE give_room_feedback_id_seq');
        $this->addSql('SELECT setval(\'give_room_feedback_id_seq\', (SELECT MAX(id) FROM give_room_feedback))');
        $this->addSql('ALTER TABLE give_room_feedback ALTER id SET DEFAULT nextval(\'give_room_feedback_id_seq\')');
        $this->addSql('ALTER TABLE give_room_feedback ALTER user_id_id SET NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ALTER room_id SET NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ALTER date_feedback SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE give_room_feedback ALTER date_feedback DROP NOT NULL');
        $this->addSql('ALTER TABLE give_room_feedback ADD CONSTRAINT give_room_feedback_user_id_fkey FOREIGN KEY (user_id_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_room_feedback ADD CONSTRAINT give_room_feedback_room_id_fkey FOREIGN KEY (room_id) REFERENCES room (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_bookmark DROP CONSTRAINT FK_7A8452D954177093');
        $this->addSql('ALTER TABLE room_bookmark DROP CONSTRAINT FK_7A8452D992741D25');
        $this->addSql('DROP INDEX bookmark_contain_pkey');
        $this->addSql('ALTER TABLE room_bookmark ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE room_bookmark ADD CONSTRAINT bookmark_contain_bookmark_id_fkey FOREIGN KEY (bookmark_id) REFERENCES bookmark (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_bookmark ADD CONSTRAINT bookmark_contain_room_id_fkey FOREIGN KEY (room_id) REFERENCES room (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_bookmark ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849559D86650F');
        $this->addSql('CREATE SEQUENCE reservation_id_seq');
        $this->addSql('SELECT setval(\'reservation_id_seq\', (SELECT MAX(id) FROM reservation))');
        $this->addSql('ALTER TABLE reservation ALTER id SET DEFAULT nextval(\'reservation_id_seq\')');
        $this->addSql('ALTER TABLE reservation ALTER user_id_id SET NOT NULL');
        $this->addSql('ALTER TABLE reservation ALTER date_reservation SET DEFAULT \'CURRENT_DATE\'');
        $this->addSql('ALTER TABLE reservation ALTER date_reservation DROP NOT NULL');
        $this->addSql('ALTER TABLE reservation ALTER is_annulled SET DEFAULT false');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT reservation_user_id_fkey FOREIGN KEY (user_id_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE partnership_id_seq');
        $this->addSql('SELECT setval(\'partnership_id_seq\', (SELECT MAX(id) FROM partnership))');
        $this->addSql('ALTER TABLE partnership ALTER id SET DEFAULT nextval(\'partnership_id_seq\')');
        $this->addSql('ALTER TABLE partnership ALTER date_proposition SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE partnership ALTER date_proposition DROP NOT NULL');
        $this->addSql('ALTER TABLE partnership ALTER partnership_type TYPE VARCHAR(200)');
        $this->addSql('ALTER TABLE partnership ALTER is_accepted SET DEFAULT false');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B3243BB18');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B296E3073');
        $this->addSql('CREATE SEQUENCE room_id_seq');
        $this->addSql('SELECT setval(\'room_id_seq\', (SELECT MAX(id) FROM room))');
        $this->addSql('ALTER TABLE room ALTER id SET DEFAULT nextval(\'room_id_seq\')');
        $this->addSql('ALTER TABLE room ALTER hotel_id SET NOT NULL');
        $this->addSql('ALTER TABLE room ALTER room_type_id SET NOT NULL');
        $this->addSql('ALTER TABLE room ALTER room_category TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE room ALTER room_name TYPE VARCHAR(200)');
        $this->addSql('ALTER TABLE room ALTER room_url_img TYPE TEXT');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT room_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT room_room_type_id_fkey FOREIGN KEY (room_type_id) REFERENCES room_type (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE resto DROP CONSTRAINT FK_892155B13243BB18');
        $this->addSql('DROP INDEX UNIQ_892155B13243BB18');
        $this->addSql('CREATE SEQUENCE resto_id_seq');
        $this->addSql('SELECT setval(\'resto_id_seq\', (SELECT MAX(id) FROM resto))');
        $this->addSql('ALTER TABLE resto ALTER id SET DEFAULT nextval(\'resto_id_seq\')');
        $this->addSql('ALTER TABLE resto ALTER hotel_id SET NOT NULL');
        $this->addSql('ALTER TABLE resto ALTER resto_url_img TYPE TEXT');
        $this->addSql('ALTER TABLE resto ADD CONSTRAINT resto_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_892155B13243BB18 ON resto (hotel_id)');
        $this->addSql('ALTER TABLE partnership_user DROP CONSTRAINT FK_62B0C6D26AE7F85');
        $this->addSql('ALTER TABLE partnership_user DROP CONSTRAINT FK_62B0C6D2A76ED395');
        $this->addSql('DROP INDEX propose_pkey');
        $this->addSql('ALTER TABLE partnership_user ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE partnership_user ADD CONSTRAINT propose_partnership_id_fkey FOREIGN KEY (partnership_id) REFERENCES partnership (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partnership_user ADD CONSTRAINT propose_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partnership_user ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE room_room_content DROP CONSTRAINT FK_A49594DA54177093');
        $this->addSql('ALTER TABLE room_room_content DROP CONSTRAINT FK_A49594DAB052D3F1');
        $this->addSql('DROP INDEX room_contain_pkey');
        $this->addSql('ALTER TABLE room_room_content ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE room_room_content ADD CONSTRAINT room_contain_room_id_fkey FOREIGN KEY (room_id) REFERENCES room (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_room_content ADD CONSTRAINT room_contain_room_content_id_fkey FOREIGN KEY (room_content_id) REFERENCES room_content (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_room_content ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE hotel_partnership DROP CONSTRAINT FK_58D79C813243BB18');
        $this->addSql('ALTER TABLE hotel_partnership DROP CONSTRAINT FK_58D79C816AE7F85');
        $this->addSql('DROP INDEX have_proposition_pkey');
        $this->addSql('ALTER TABLE hotel_partnership ADD id SERIAL NOT NULL');
        $this->addSql('ALTER TABLE hotel_partnership ADD CONSTRAINT have_proposition_partnership_id_fkey FOREIGN KEY (partnership_id) REFERENCES partnership (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_partnership ADD CONSTRAINT have_proposition_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hotel_partnership ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE user_type_id_seq');
        $this->addSql('SELECT setval(\'user_type_id_seq\', (SELECT MAX(id) FROM user_type))');
        $this->addSql('ALTER TABLE user_type ALTER id SET DEFAULT nextval(\'user_type_id_seq\')');
        $this->addSql('ALTER TABLE user_type ALTER user_type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE give_hotel_feedback DROP CONSTRAINT FK_FF08E90D9D86650F');
        $this->addSql('ALTER TABLE give_hotel_feedback DROP CONSTRAINT FK_FF08E90D3243BB18');
        $this->addSql('CREATE SEQUENCE give_hotel_feedback_id_seq');
        $this->addSql('SELECT setval(\'give_hotel_feedback_id_seq\', (SELECT MAX(id) FROM give_hotel_feedback))');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER id SET DEFAULT nextval(\'give_hotel_feedback_id_seq\')');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER user_id_id SET NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER hotel_id SET NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER date_feedback SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE give_hotel_feedback ALTER date_feedback DROP NOT NULL');
        $this->addSql('ALTER TABLE give_hotel_feedback ADD CONSTRAINT give_hotel_feedback_user_id_fkey FOREIGN KEY (user_id_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE give_hotel_feedback ADD CONSTRAINT give_hotel_feedback_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE media_id_seq');
        $this->addSql('SELECT setval(\'media_id_seq\', (SELECT MAX(id) FROM media))');
        $this->addSql('ALTER TABLE media ALTER id SET DEFAULT nextval(\'media_id_seq\')');
        $this->addSql('ALTER TABLE bookmark DROP CONSTRAINT FK_DA62921D9D86650F');
        $this->addSql('CREATE SEQUENCE bookmark_id_seq');
        $this->addSql('SELECT setval(\'bookmark_id_seq\', (SELECT MAX(id) FROM bookmark))');
        $this->addSql('ALTER TABLE bookmark ALTER id SET DEFAULT nextval(\'bookmark_id_seq\')');
        $this->addSql('ALTER TABLE bookmark ALTER user_id_id SET NOT NULL');
        $this->addSql('ALTER TABLE bookmark ADD CONSTRAINT bookmark_user_id_fkey FOREIGN KEY (user_id_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DB83297E7');
        $this->addSql('CREATE SEQUENCE payment_id_seq');
        $this->addSql('SELECT setval(\'payment_id_seq\', (SELECT MAX(id) FROM payment))');
        $this->addSql('ALTER TABLE payment ALTER id SET DEFAULT nextval(\'payment_id_seq\')');
        $this->addSql('ALTER TABLE payment ALTER reservation_id SET NOT NULL');
        $this->addSql('ALTER TABLE payment ALTER date_payment SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE payment ALTER method_payment TYPE VARCHAR(150)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT payment_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
