insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (1, 'Fusce vitae semper nunc. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.', '2023-03-07', 6, 71, 24);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (2, 'leo neque tristique nunc', '2023-04-15', 9, 94, 15);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (3, 'nunc vel aliquam ultricies', '2022-08-12', 6, 43, 50);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (4, 'Lorem ipsum dolor sit amet', '2023-01-01', 2, 32, 57);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (5, 'nec ultrices sem urna vel nunc.', '2023-02-18', 2, 64, 7);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (6, 'leo neque tristique nunc', '2023-04-01', 1, 42, 58);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (7, 'leo neque tristique nunc', '2022-08-24', 5, 72, 9);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (8, 'nec ultrices sem urna vel nunc.', '2023-02-03', 3, 52, 34);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (9, 'nec ultrices sem urna vel nunc.', '2022-11-26', 9, 38, 49);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (10, 'leo neque tristique nunc', '2022-08-20', 1, 44, 37);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (11, 'Donec euismod', '2023-04-12', 7, 32, 58);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (12, 'Donec euismod', '2022-10-25', 1, 12, 18);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (13, 'Curabitur euismod', '2023-05-07', 5, 76, 45);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (14, 'leo neque tristique nunc', '2023-01-20', 4, 34, 36);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (15, 'Donec euismod', '2022-07-21', 3, 88, 18);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (16, 'nunc vel aliquam ultricies', '2022-12-01', 3, 45, 46);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (17, 'nec ultrices sem urna vel nunc.', '2023-03-09', 4, 38, 31);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (18, 'Donec euismod', '2023-04-15', 1, 27, 56);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (19, 'nec ultrices sem urna vel nunc.', '2022-11-23', 2, 28, 16);
insert into give_hotel_feedbackk (id, text_body, date_feedback, note, user_id, hotel_id) values (20, 'leo neque tristique nunc', '2023-05-04', 10, 32, 41);
