insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (1, 'Quisque sit amet nisl in nunc lacinia tincidunt.', '2029-02-02', 7, 76, 30);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (2, 'Donec auctor', '2022-12-19', 5, 12, 42);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (3, 'consectetur adipiscing elit.', '2026-09-12', 8, 100, 45);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (4, 'lorem et ultricies lacinia', '2028-11-30', 1, 80, 18);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (5, 'Vivamus non nunc nec mi tincidunt tincidunt.', '2028-08-09', 2, 35, 37);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (6, 'sed luctus mauris urna ac lectus.', '2029-10-09', 2, 66, 48);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (7, 'Fusce auctor', '2029-12-06', 5, 84, 36);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (8, 'Vivamus non nunc nec mi tincidunt tincidunt.', '2029-03-16', 1, 42, 36);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (9, 'sed luctus mauris urna ac lectus.', '2023-06-28', 6, 84, 4);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (10, 'Nullam eget felis ut purus condimentum fringilla.', '2023-05-09', 1, 61, 8);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (11, 'id consequat neque neque vitae metus.', '2023-07-24', 1, 49, 44);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (12, 'id consequat neque neque vitae metus.', '2023-04-20', 2, 7, 3);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (13, 'Fusce auctor', '2026-08-24', 10, 92, 2);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (14, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;', '2022-08-05', 2, 91, 40);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (15, 'tortor nisl lacinia nunc', '2023-11-12', 6, 46, 55);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (16, 'consectetur adipiscing elit.', '2023-12-24', 6, 28, 54);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (17, 'Vivamus non nunc nec mi tincidunt tincidunt.', '2022-09-01', 3, 13, 27);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (18, 'Curabitur euismod', '2024-11-17', 8, 92, 60);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (19, 'consectetur adipiscing elit.', '2027-03-20', 1, 23, 56);
insert into give_hotel_feedback (id, text_body, date_feedback, note, user_id, hotel_id) values (20, 'Sed ac justo in nunc tincidunt tincidunt.', '2022-11-24', 2, 36, 58);
