insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (1, 'sunt in culpa qui officia deserunt mollit anim id est laborum.', '2023-04-18', 4, 74, 18);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (2, 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.', '2022-10-03', 5, 15, 59);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (3, 'adipisci velit.', '2022-11-30', 6, 89, 58);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (4, 'consectetur', '2023-02-04', 9, 34, 45);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (5, 'consectetur', '2023-05-13', 6, 13, 41);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (6, 'sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-09-04', 2, 3, 46);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (7, 'Excepteur sint occaecat cupidatat non proident', '2022-09-10', 8, 78, 21);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (8, 'Excepteur sint occaecat cupidatat non proident', '2022-08-15', 2, 79, 45);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (9, 'qui dolorem ipsum quia dolor sit amet', '2023-03-30', 6, 44, 16);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (10, 'consectetur adipiscing elit.', '2023-07-12', 7, 100, 3);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (11, 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.', '2023-02-20', 5, 61, 21);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (12, 'consectetur', '2023-01-21', 9, 75, 1);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (13, 'sunt in culpa qui officia deserunt mollit anim id est laborum.', '2023-06-12', 3, 61, 2);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (14, 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.', '2022-08-16', 8, 26, 58);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (15, 'sunt in culpa qui officia deserunt mollit anim id est laborum.', '2022-09-01', 1, 20, 30);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (16, 'qui dolorem ipsum quia dolor sit amet', '2023-03-07', 4, 38, 35);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (17, 'Neque porro quisquam est', '2022-07-30', 3, 79, 55);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (18, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.', '2022-10-28', 3, 55, 60);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (19, 'qui dolorem ipsum quia dolor sit amet', '2023-04-19', 1, 1, 34);
insert into give_room_feedback (id, text_body, date_feedback, note, user_id, room_id) values (20, 'consectetur', '2023-03-19', 10, 82, 43);
