insert into hotel (id, hotel_name, address, city, state, phone_number) values (1, 'Nikolaus, Hyatt and Schinner', '2537 Almo Alley', 'Birmingham', 'Alabama', '(205) 9747933');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (2, 'Metz Group', '25 Meadow Vale Street', 'Birmingham', 'Alabama', '(205) 1839527');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (3, 'Schowalter-Crooks', '113 Stone Corner Lane', 'Montgomery', 'Alabama', '(334) 8964871');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (4, 'Homenick, Lebsack and Reinger', '9 Dryden Avenue', 'Birmingham', 'Alabama', '(205) 8512281');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (5, 'Langosh LLC', '035 Pleasure Drive', 'Birmingham', 'Alabama', '(205) 2259029');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (6, 'Mayert LLC', '53963 Ridgeview Plaza', 'Huntsville', 'Alabama', '(256) 5059695');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (7, 'Schoen Group', '5627 Mesta Park', 'Mobile', 'Alabama', '(251) 8954674');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (8, 'Bogisich-Monahan', '19 Memorial Alley', 'Birmingham', 'Alabama', '(205) 9456299');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (9, 'O''Conner, Greenfelder and Fisher', '95704 Londonderry Point', 'Montgomery', 'Alabama', '(334) 2255500');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (10, 'Kutch LLC', '3 Russell Circle', 'Birmingham', 'Alabama', '(205) 6892656');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (11, 'Ruecker, Kihn and Bode', '9 Maywood Circle', 'Mobile', 'Alabama', '(251) 1581444');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (12, 'Marks, Beier and Baumbach', '7 Dapin Court', 'Mobile', 'Alabama', '(251) 6578373');

insert into hotel (id, hotel_name, address, city, state, phone_number) values (13, 'Roberts, Wolf and Spinka', '96 Sundown Place', 'Huntsville', 'Alabama', '(256) 6462490');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (14, 'Kling, Walter and Hickle', '779 Coleman Court', 'Birmingham', 'Alabama', '(205) 4710065');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (15, 'Lowe, Dibbert and Feest', '03211 Del Mar Court', 'Birmingham', 'Alabama', '(205) 5998579');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (16, 'Gutmann Group', '116 Summerview Pass', 'Birmingham', 'Alabama', '(205) 4401777');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (17, 'Schaefer, Will and Grimes', '17 Hudson Hill', 'Montgomery', 'Alabama', '(334) 9728371');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (18, 'Prosacco, Green and Johnson', '50688 Mifflin Street', 'Birmingham', 'Alabama', '(205) 3089832');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (19, 'Gottlieb, Nicolas and Sauer', '0 Dexter Avenue', 'Birmingham', 'Alabama', '(205) 3859796');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (20, 'Fadel, Wiza and Kuphal', '55 Graedel Street', 'Montgomery', 'Alabama', '(334) 5395013');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (21, 'Greenholt and Sons', '15703 Russell Pass', 'Huntsville', 'Alabama', '(256) 5101064');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (22, 'Crist and Sons', '0 Mayer Junction', 'Birmingham', 'Alabama', '(205) 8825556');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (23, 'Hudson Group', '15828 Kropf Road', 'Birmingham', 'Alabama', '(334) 1279180');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (24, 'Collins Group', '507 Marquette Junction', 'Birmingham', 'Alabama', '(205) 3345588');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (25, 'Denesik LLC', '452 Hermina Way', 'Huntsville', 'Alabama', '(256) 1871040');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (26, 'Mueller Inc', '585 Fieldstone Court', 'Mobile', 'Alabama', '(251) 6602573');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (27, 'Braun-Ferry', '2 Vernon Place', 'Montgomery', 'Alabama', '(334) 6579756');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (28, 'Pfeffer LLC', '7505 Red Cloud Junction', 'Montgomery', 'Alabama', '(334) 4553133');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (29, 'Schmeler and Sons', '5355 Hazelcrest Trail', 'Birmingham', 'Alabama', '(205) 8317657');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (30, 'Zieme-Wolff', '120 Ronald Regan Way', 'Mobile', 'Alabama', '(251) 1387442');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (31, 'Gottlieb, Hintz and Torp', '72929 Burning Wood Avenue', 'Mobile', 'Alabama', '(251) 6864358');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (32, 'Macejkovic, Lang and Bins', '295 Gateway Drive', 'Birmingham', 'Alabama', '(205) 5045050');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (33, 'Medhurst-Abernathy', '743 Burrows Place', 'Mobile', 'Alabama', '(251) 6824742');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (34, 'McLaughlin-Watsica', '070 Lotheville Court', 'Huntsville', 'Alabama', '(256) 2846852');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (35, 'Murazik Group', '3031 Dayton Plaza', 'Montgomery', 'Alabama', '(334) 5299671');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (36, 'Hamill Group', '98526 Sutherland Road', 'Birmingham', 'Alabama', '(205) 9720106');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (37, 'McKenzie-Bahringer', '5429 Warner Way', 'Birmingham', 'Alabama', '(205) 6257471');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (38, 'Lang and Sons', '09613 Arrowood Street', 'Anniston', 'Alabama', '(256) 7532072');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (39, 'O''Conner, McKenzie and Weissnat', '9 Dottie Plaza', 'Mobile', 'Alabama', '(251) 9837525');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (40, 'Lindgren, Lindgren and Rowe', '79621 Aberg Street', 'Birmingham', 'Alabama', '(205) 7915210');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (41, 'Raynor-Jacobi', '44084 Clemons Parkway', 'Birmingham', 'Alabama', '(205) 6517047');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (42, 'Williamson LLC', '9 Cordelia Parkway', 'Birmingham', 'Alabama', '(205) 2711098');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (43, 'Schneider, McKenzie and Schmitt', '768 Hoard Street', 'Birmingham', 'Alabama', '(205) 4478248');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (44, 'Hettinger Inc', '670 Monica Crossing', 'Birmingham', 'Alabama', '(205) 2184518');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (45, 'Heaney, Larson and Kutch', '1914 Texas Place', 'Tuscaloosa', 'Alabama', '(205) 1857620');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (46, 'Harris Inc', '596 Susan Pass', 'Mobile', 'Alabama', '(251) 6711330');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (47, 'Pouros, Trantow and Predovic', '01 Hansons Center', 'Huntsville', 'Alabama', '(256) 6321942');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (48, 'Rosenbaum, Douglas and Trantow', '7669 Forest Court', 'Huntsville', 'Alabama', '(256) 1992087');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (49, 'Shanahan, Dibbert and Okuneva', '213 Washington Drive', 'Huntsville', 'Alabama', '(256) 8900228');
insert into hotel (id, hotel_name, address, city, state, phone_number) values (50, 'Wintheiser-Douglas', '58100 8th Court', 'Birmingham', 'Alabama', '(205) 9942807');
