insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (1, '2022-10-16 08:26:35', 'joint venture', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (2, '2022-11-25 06:12:14', 'united', false, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (3, '2022-10-13 23:38:46', 'alliance', false, 'keep it up!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (4, '2022-12-05 19:18:16', 'equitable', false, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (5, '2022-09-08 23:30:02', 'equitable', false, 'Don''t forget to smile.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (6, '2023-06-15 16:49:07', 'shared', false, 'Don''t forget to smile.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (7, '2022-09-06 08:17:20', 'alliance', true, 'This is a test message.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (8, '2022-07-31 14:58:36', 'alliance', true, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (9, '2022-10-05 05:45:27', 'joint venture', true, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (10, '2023-03-30 11:12:13', 'strategic', true, 'Hope you''re having a great day.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (11, '2023-06-27 01:36:55', 'united', true, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (12, '2023-04-15 08:36:08', 'strategic', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (13, '2022-12-11 07:12:09', 'shared', false, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (14, '2022-08-28 13:59:17', 'united', true, 'Don''t forget to smile.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (15, '2022-07-19 21:27:08', 'mutual', false, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (16, '2023-03-20 16:17:20', 'mutual', true, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (17, '2022-08-28 13:55:42', 'synergistic', false, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (18, '2022-08-09 12:31:11', 'shared', false, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (19, '2022-09-07 15:59:22', 'mutual', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (20, '2023-07-05 00:21:55', 'strategic', true, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (21, '2023-07-07 06:23:01', 'united', true, 'Lorem ipsum dolor sit amet.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (22, '2023-05-06 11:03:00', 'strategic', true, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (23, '2023-03-11 17:11:32', 'shared', true, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (24, '2023-02-26 17:26:31', 'united', false, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (25, '2023-05-31 20:06:39', 'joint venture', false, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (26, '2023-05-16 20:12:19', 'shared', true, 'Just wanted to say hi!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (27, '2023-01-04 23:55:40', 'strategic', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (28, '2022-08-25 16:59:22', 'alliance', false, 'Lorem ipsum dolor sit amet.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (29, '2023-07-11 08:22:21', 'strategic', false, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (30, '2022-09-24 21:36:46', 'collaborative', true, 'Don''t forget to smile.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (31, '2022-07-21 03:59:53', 'joint venture', false, 'Don''t forget to smile.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (32, '2023-03-30 04:42:38', 'united', false, 'Lorem ipsum dolor sit amet.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (33, '2022-09-08 13:47:12', 'collaborative', false, 'Remember to stay hydrated!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (34, '2022-11-30 07:24:36', 'alliance', true, 'keep it up!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (35, '2023-02-03 21:32:48', 'cooperative', true, 'Hope you''re having a great day.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (36, '2023-01-21 16:35:31', 'alliance', true, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (37, '2023-02-27 13:23:56', 'equitable', false, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (38, '2022-10-30 17:47:17', 'mutual', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (39, '2022-10-30 19:24:38', 'shared', true, 'Remember to stay hydrated!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (40, '2022-10-26 17:40:57', 'shared', true, 'Remember to stay hydrated!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (41, '2022-09-20 04:45:44', 'shared', true, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (42, '2023-03-28 00:14:51', 'equitable', false, 'Sending positive vibes your way.');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (43, '2022-12-21 03:54:36', 'strategic', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (44, '2022-07-19 08:44:51', 'joint venture', true, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (45, '2023-03-01 05:16:20', 'collaborative', true, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (46, '2023-05-16 05:49:10', 'collaborative', false, 'Hello');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (47, '2023-05-17 13:18:11', 'strategic', false, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (48, '2022-09-19 10:35:01', 'cooperative', true, 'how are you?');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (49, '2023-04-29 18:50:05', 'alliance', true, 'Wishing you a wonderful week!');
insert into partnership (id, date_proposition, partnership_type, is_accepted, message) values (50, '2023-02-10 20:23:52', 'mutual', false, 'Just wanted to say hi!');
