insert into promotion (id, start_date, end_date, reduction, description) values (1, '2022-12-08', '2024-10-20', 94, 'Unspecified injury of brachial artery, left side, subsequent encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (2, '2023-07-26', '2024-01-24', 17, 'Displaced fracture of base of unspecified metacarpal bone, subsequent encounter for fracture with nonunion');
insert into promotion (id, start_date, end_date, reduction, description) values (3, '2023-03-24', '2024-12-26', 82, 'Blister (nonthermal) of abdomen, lower back, pelvis and external genitals');
insert into promotion (id, start_date, end_date, reduction, description) values (4, '2022-04-25', '2024-03-24', 45, 'Pedestrian on other gliding-type pedestrian conveyance colliding with stationary object, initial encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (5, '2022-03-10', '2024-08-09', 79, 'Sprain of right coracohumeral (ligament)');
insert into promotion (id, start_date, end_date, reduction, description) values (6, '2022-11-25', '2024-07-08', 10, 'Unspecified physeal fracture of lower end of humerus, unspecified arm, subsequent encounter for fracture with malunion');
insert into promotion (id, start_date, end_date, reduction, description) values (7, '2022-07-13', '2024-04-03', 55, 'Nursing home as the place of occurrence of the external cause');
insert into promotion (id, start_date, end_date, reduction, description) values (8, '2023-05-17', '2024-09-09', 93, 'Other congenital malformations of diaphragm');
insert into promotion (id, start_date, end_date, reduction, description) values (9, '2023-02-14', '2024-03-08', 48, 'Unspecified nondisplaced fracture of fourth cervical vertebra');
insert into promotion (id, start_date, end_date, reduction, description) values (10, '2022-07-08', '2024-09-26', 58, 'War operations involving combat using blunt or piercing object, civilian, subsequent encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (11, '2022-07-28', '2024-11-19', 79, 'Blister (nonthermal) of right front wall of thorax');

insert into promotion (id, start_date, end_date, reduction, description) values (12, '2022-07-28', '2024-01-05', 51, 'Unspecified injury of portal vein, subsequent encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (13, '2022-09-15', '2024-11-06', 98, 'Laceration without foreign body of unspecified thumb without damage to nail, subsequent encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (14, '2022-03-27', '2024-09-24', 49, 'Unspecified injury of superior mesenteric vein, subsequent encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (15, '2022-07-12', '2024-02-02', 11, 'Displaced fracture of epiphysis (separation) (upper) of right femur, subsequent encounter for open fracture type I or II with routine healing');
insert into promotion (id, start_date, end_date, reduction, description) values (16, '2022-09-13', '2024-09-17', 51, 'Nondisplaced fracture of lateral malleolus of right fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into promotion (id, start_date, end_date, reduction, description) values (17, '2023-05-07', '2024-10-13', 98, 'Unspecified displaced fracture of surgical neck of left humerus, initial encounter for closed fracture');
insert into promotion (id, start_date, end_date, reduction, description) values (18, '2023-04-21', '2024-05-11', 87, 'Unspecified focal traumatic brain injury with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness, sequela');
insert into promotion (id, start_date, end_date, reduction, description) values (19, '2022-10-09', '2024-03-20', 62, 'Unspecified injury of unspecified tibial artery, right leg, initial encounter');
insert into promotion (id, start_date, end_date, reduction, description) values (20, '2023-02-21', '2024-05-21', 80, 'Toxic effect of other specified gases, fumes and vapors, assault, initial encounter');
