insert into resto (id, speciality, resto_url_img, description, hotel_id) values (1, 'Aligot', 'http://dummyimage.com/111x100.png/5fa2dd/ffffff', 'Myalgia and myositis NOS', 15);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (2, 'Parsley snails', 'http://dummyimage.com/175x100.png/cc0000/ffffff', 'Mv n-traf NEC-anim rider', 11);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (3, 'quiche Lorraine', 'http://dummyimage.com/242x100.png/ff4444/ffffff', 'Personal bathing/shower', 36);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (4, 'Stew', 'http://dummyimage.com/118x100.png/ff4444/ffffff', 'Voyeurism', 39);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (5, 'Stew', 'http://dummyimage.com/121x100.png/dddddd/000000', 'Adjustment reaction NOS', 21);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (6, 'Oysters', 'http://dummyimage.com/208x100.png/5fa2dd/ffffff', 'Status oth spcf crdc dvc', 22);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (7, 'Rice', 'http://dummyimage.com/120x100.png/dddddd/000000', 'Oth VD chlm trch unsp st', 50);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (8, 'Aligot', 'http://dummyimage.com/225x100.png/dddddd/000000', 'Mal neo brain stem', 11);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (9, 'Stew', 'http://dummyimage.com/247x100.png/ff4444/ffffff', 'Joint effusion-l/leg', 33);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (10, 'Ravitoto', 'http://dummyimage.com/160x100.png/dddddd/000000', 'Urticaria NEC', 34);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (11, 'Breton pancakes', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 'Sprain of nasal septum', 22);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (12, 'Stew', 'http://dummyimage.com/121x100.png/dddddd/000000', 'Hx-allergy NEC', 30);

insert into resto (id, speciality, resto_url_img, description, hotel_id) values (13, 'Stew', 'http://dummyimage.com/165x100.png/cc0000/ffffff', 'Opioid/other dep-unspec', 43);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (14, 'Romazava', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 'Breech del/extrac aff NB', 22);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (15, 'Oysters', 'http://dummyimage.com/209x100.png/ff4444/ffffff', 'Foreign body in larynx', 16);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (16, 'The bouillabaisse', 'http://dummyimage.com/132x100.png/ff4444/ffffff', 'Leukocytopenia NOS', 49);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (17, 'Rice', 'http://dummyimage.com/141x100.png/ff4444/ffffff', 'Foc choroiditis post NEC', 10);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (18, 'Mofo baolina', 'http://dummyimage.com/216x100.png/dddddd/000000', 'Ac peptic ulc w hem-obst', 29);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (19, 'Rice', 'http://dummyimage.com/222x100.png/cc0000/ffffff', 'Meningococc myocarditis', 20);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (20, 'quiche Lorraine', 'http://dummyimage.com/144x100.png/dddddd/000000', 'Female orgasmic disorder', 40);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (21, 'Masikita', 'http://dummyimage.com/198x100.png/cc0000/ffffff', 'Ctrct frgmt frm ctr surg', 5);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (22, 'Rice', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'Monofixation syndrome', 31);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (23, 'Breton pancakes', 'http://dummyimage.com/140x100.png/ff4444/ffffff', 'Uncert behavior neo NOS', 25);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (24, 'Rice', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 'Rheumatoid lung', 11);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (25, 'Rice', 'http://dummyimage.com/198x100.png/ff4444/ffffff', 'Reticulosarcoma inguin', 5);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (26, 'Koba', 'http://dummyimage.com/188x100.png/cc0000/ffffff', 'Pelv perit endometriosis', 16);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (27, 'Masikita', 'http://dummyimage.com/227x100.png/dddddd/000000', 'Post traumatic seizures', 2);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (28, 'Aligot', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff', 'Proteus enteritis', 14);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (29, 'The bouillabaisse', 'http://dummyimage.com/187x100.png/ff4444/ffffff', 'Ot VD chlm trch unspf gu', 25);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (30, 'Koba', 'http://dummyimage.com/129x100.png/dddddd/000000', 'Varicose vulva-antepart', 1);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (31, 'steak tartare', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff', 'Leukoplakia oral mucosa', 19);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (32, 'Koba', 'http://dummyimage.com/152x100.png/dddddd/000000', 'Fx phalanx, foot-closed', 3);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (33, 'Mofo baolina', 'http://dummyimage.com/172x100.png/cc0000/ffffff', 'Opn skul vlt fx w/o coma', 34);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (34, 'Ravitoto', 'http://dummyimage.com/136x100.png/ff4444/ffffff', 'Pain in limb', 20);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (35, 'Mofo baolina', 'http://dummyimage.com/249x100.png/dddddd/000000', 'Idiopathc trans myelitis', 41);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (36, 'Stew', 'http://dummyimage.com/228x100.png/5fa2dd/ffffff', 'Malig melanoma skin NEC', 30);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (37, 'Breton pancakes', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff', 'Choroidal detachment NOS', 6);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (38, 'Masikita', 'http://dummyimage.com/122x100.png/dddddd/000000', 'Open wound site NOS', 17);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (39, 'Mocary', 'http://dummyimage.com/202x100.png/dddddd/000000', 'Sprain lumbar region', 48);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (40, 'Pickle', 'http://dummyimage.com/135x100.png/5fa2dd/ffffff', 'Abnormal sputum', 25);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (41, 'steak tartare', 'http://dummyimage.com/116x100.png/cc0000/ffffff', 'Acq pelvic deformity', 10);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (42, 'steak tartare', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', 'Benign neopl rectum/anus', 14);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (43, 'Stew', 'http://dummyimage.com/235x100.png/ff4444/ffffff', 'TB laryngitis-exam unkn', 17);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (44, 'quiche Lorraine', 'http://dummyimage.com/214x100.png/cc0000/ffffff', 'Oth cond due to sex chrm', 29);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (45, 'Aligot', 'http://dummyimage.com/223x100.png/ff4444/ffffff', 'Alcoholic polyneuropathy', 40);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (46, 'Aligot', 'http://dummyimage.com/230x100.png/dddddd/000000', 'Cord entangle NEC-unspec', 48);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (47, 'Breton pancakes', 'http://dummyimage.com/136x100.png/cc0000/ffffff', 'Abdmnal rgdt unspcf site', 8);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (48, 'Ravitoto', 'http://dummyimage.com/110x100.png/cc0000/ffffff', 'Fet grwth ret 1250-1499g', 27);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (49, 'Parsley snails', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 'Lymphoid mal NEC head', 45);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (50, 'quiche Lorraine', 'http://dummyimage.com/141x100.png/cc0000/ffffff', 'Inflamm polyarthrop NOS', 6);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (51, 'Rice', 'http://dummyimage.com/243x100.png/dddddd/000000', '3rd deg burn chin', 24);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (52, 'Parsley snails', 'http://dummyimage.com/146x100.png/cc0000/ffffff', 'Op skl base fx-deep coma', 12);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (53, 'Oysters', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'Gonococcal bursitis', 1);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (54, 'Parsley snails', 'http://dummyimage.com/196x100.png/dddddd/000000', 'Benign neo uterus NEC', 4);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (55, 'Mocary', 'http://dummyimage.com/113x100.png/dddddd/000000', 'Illeg ab w embolism-unsp', 10);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (56, 'Koba', 'http://dummyimage.com/226x100.png/dddddd/000000', 'Psychogenic disorder NOS', 31);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (57, 'quiche Lorraine', 'http://dummyimage.com/196x100.png/cc0000/ffffff', 'Joint replaced shoulder', 20);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (58, 'steak tartare', 'http://dummyimage.com/208x100.png/5fa2dd/ffffff', 'Clothing fire not in bld', 4);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (59, 'Mocary', 'http://dummyimage.com/166x100.png/dddddd/000000', 'Fx metacarpal shaft-open', 44);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (60, 'Rice', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'Fem pelvic periton adhes', 39);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (61, 'steak tartare', 'http://dummyimage.com/148x100.png/dddddd/000000', 'Congenital chordee', 1);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (62, 'Oysters', 'http://dummyimage.com/141x100.png/5fa2dd/ffffff', 'Nasal bone fx-open', 47);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (63, 'Masikita', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff', 'Hyp ht/kd NOS I-IV w hf', 31);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (64, 'Parsley snails', 'http://dummyimage.com/142x100.png/cc0000/ffffff', 'Tick-borne ricketts NEC', 18);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (65, 'Rice', 'http://dummyimage.com/115x100.png/dddddd/000000', 'Inadequate housing', 4);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (66, 'Pickle', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'Abrasion trunk-infected', 30);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (67, 'Oysters', 'http://dummyimage.com/185x100.png/cc0000/ffffff', 'Endos dentl imp fail NEC', 15);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (68, 'Rice', 'http://dummyimage.com/138x100.png/ff4444/ffffff', 'Prim central sleep apnea', 10);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (69, 'Aligot', 'http://dummyimage.com/152x100.png/dddddd/000000', 'Mycoses NEC & NOS', 44);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (70, 'Mocary', 'http://dummyimage.com/200x100.png/5fa2dd/ffffff', 'Deep 3rd deg burn toe', 16);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (71, 'Romazava', 'http://dummyimage.com/103x100.png/ff4444/ffffff', 'AMI lateral NEC, subseq', 11);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (72, 'Parsley snails', 'http://dummyimage.com/115x100.png/cc0000/ffffff', 'Crbl art oc NOS wo infrc', 12);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (73, 'Aligot', 'http://dummyimage.com/223x100.png/ff4444/ffffff', 'Med rhomboid glossitis', 18);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (74, 'Stew', 'http://dummyimage.com/124x100.png/ff4444/ffffff', 'Reentrant mv coll-pasngr', 5);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (75, 'Pickle', 'http://dummyimage.com/200x100.png/cc0000/ffffff', 'Cysts of jaws NEC', 13);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (76, 'Masikita', 'http://dummyimage.com/183x100.png/dddddd/000000', 'Capsular cataract', 9);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (77, 'Koba', 'http://dummyimage.com/173x100.png/dddddd/000000', 'Individ sports,athletics', 36);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (78, 'Mocary', 'http://dummyimage.com/201x100.png/dddddd/000000', 'T1-t6 fx-cl/cord inj NEC', 49);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (79, 'Stew', 'http://dummyimage.com/114x100.png/ff4444/ffffff', 'Injury ovarian artery', 35);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (80, 'Pickle', 'http://dummyimage.com/248x100.png/ff4444/ffffff', 'Inj musculocutan nerve', 50);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (81, 'Parsley snails', 'http://dummyimage.com/118x100.png/dddddd/000000', 'Mal neo pancreatic duct', 45);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (82, 'Aligot', 'http://dummyimage.com/195x100.png/ff4444/ffffff', 'Drug dermatitis NOS', 46);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (83, 'Masikita', 'http://dummyimage.com/157x100.png/ff4444/ffffff', 'Allerg rhinitis-cat/dog', 3);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (84, 'Oysters', 'http://dummyimage.com/107x100.png/dddddd/000000', 'Enophthalmos d/t trauma', 48);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (85, 'The bouillabaisse', 'http://dummyimage.com/133x100.png/cc0000/ffffff', 'Complcation-insulin pump', 45);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (86, 'Romazava', 'http://dummyimage.com/215x100.png/ff4444/ffffff', 'Routine physicl lab exam', 13);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (87, 'Oysters', 'http://dummyimage.com/102x100.png/ff4444/ffffff', 'Pilates', 31);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (88, 'Koba', 'http://dummyimage.com/243x100.png/dddddd/000000', 'Injury to optic chiasm', 7);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (89, 'Mocary', 'http://dummyimage.com/207x100.png/cc0000/ffffff', 'Crush inj scapul region', 32);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (90, 'Rice', 'http://dummyimage.com/209x100.png/cc0000/ffffff', 'Histoplasmosis NOS', 16);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (91, 'Mocary', 'http://dummyimage.com/222x100.png/5fa2dd/ffffff', 'Mult myeloma in relapse', 20);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (92, 'Rice', 'http://dummyimage.com/213x100.png/dddddd/000000', 'Gonococcal peritonitis', 21);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (93, 'steak tartare', 'http://dummyimage.com/150x100.png/ff4444/ffffff', 'Ovarian dysfunction NEC', 36);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (94, 'Pickle', 'http://dummyimage.com/136x100.png/dddddd/000000', 'Enophthalmos d/t trauma', 29);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (95, 'Ravitoto', 'http://dummyimage.com/172x100.png/dddddd/000000', 'Roller coaster riding', 41);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (96, 'Masikita', 'http://dummyimage.com/101x100.png/dddddd/000000', 'Malignant neo palate NOS', 25);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (97, 'Mocary', 'http://dummyimage.com/212x100.png/5fa2dd/ffffff', 'Infertility-tubal origin', 26);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (98, 'quiche Lorraine', 'http://dummyimage.com/168x100.png/dddddd/000000', 'Drug dependence-postpart', 14);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (99, 'steak tartare', 'http://dummyimage.com/128x100.png/cc0000/ffffff', 'Ice Skating', 6);
insert into resto (id, speciality, resto_url_img, description, hotel_id) values (100, 'Ravitoto', 'http://dummyimage.com/156x100.png/dddddd/000000', 'Adenoid vegetations', 26);
