insert into room_type (id, type) values (1, 'Simple room');
insert into room_type (id, type) values (2, 'Double room');
insert into room_type (id, type) values (3, 'Twin bedroom');
insert into room_type (id, type) values (4, 'Triple room');
insert into room_type (id, type) values (5, 'Following');
insert into room_type (id, type) values (6, 'Family room');
insert into room_type (id, type) values (7, 'Connecting room');
insert into room_type (id, type) values (8, 'Room with a view');
insert into room_type (id, type) values (9, 'Executive room');
insert into room_type (id, type) values (10, 'Room accessible to people with reduced mobility');
