insert into room_content (id, content_name, content_url_img) values (1, 'Hand towels', 'http://dummyimage.com/140x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (2, 'Wine glasses', 'http://dummyimage.com/198x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (3, 'Television', 'http://dummyimage.com/131x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (4, 'Duvet', 'http://dummyimage.com/177x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (5, 'Shower gel', 'http://dummyimage.com/148x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (6, 'Lamp', 'http://dummyimage.com/212x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (7, 'Slippers', 'http://dummyimage.com/203x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (8, 'Wi-Fi router', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (9, 'Hangers', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (10, 'Mini fridge', 'http://dummyimage.com/128x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (11, 'Writing materials', 'http://dummyimage.com/131x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (12, 'Tea kettle', 'http://dummyimage.com/141x100.png/ff4444/ffffff');

insert into room_content (id, content_name, content_url_img) values (13, 'Ethernet cable', 'http://dummyimage.com/162x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (14, 'Cups', 'http://dummyimage.com/131x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (15, 'Ethernet cable', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (16, 'Blankets', 'http://dummyimage.com/101x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (17, 'Alarm clock', 'http://dummyimage.com/187x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (18, 'Shoe polish kit', 'http://dummyimage.com/248x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (19, 'Blinds', 'http://dummyimage.com/235x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (20, 'Shampoo', 'http://dummyimage.com/196x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (21, 'USB ports', 'http://dummyimage.com/182x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (22, 'Bathrobe', 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (23, 'Microwave', 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (24, 'Pen/pencil', 'http://dummyimage.com/147x100.png/dddddd/000000');

insert into room_content (id, content_name, content_url_img) values (25, 'Dishware', 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (26, 'Vanity kit', 'http://dummyimage.com/115x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (27, 'Power outlets', 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (28, 'Wall art', 'http://dummyimage.com/178x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (29, 'Kitchenette', 'http://dummyimage.com/228x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (30, 'Dining table', 'http://dummyimage.com/151x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (31, 'Room directory', 'http://dummyimage.com/247x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (32, 'Blinds', 'http://dummyimage.com/199x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (33, 'Jacuzzi', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (34, 'Heater', 'http://dummyimage.com/138x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (35, 'Bed', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (36, 'Kitchenette', 'http://dummyimage.com/241x100.png/ff4444/ffffff');

insert into room_content (id, content_name, content_url_img) values (37, 'Dining chairs', 'http://dummyimage.com/118x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (38, 'Reading lights', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (39, 'Power outlets', 'http://dummyimage.com/115x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (40, 'USB ports', 'http://dummyimage.com/247x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (41, 'Telephone', 'http://dummyimage.com/131x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (42, 'Safe', 'http://dummyimage.com/129x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (43, 'Bath mat', 'http://dummyimage.com/122x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (44, 'Blankets', 'http://dummyimage.com/236x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (45, 'Bathrobe', 'http://dummyimage.com/219x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (46, 'Trash bin', 'http://dummyimage.com/200x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (47, 'Tea kettle', 'http://dummyimage.com/240x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (48, 'Shelves', 'http://dummyimage.com/114x100.png/dddddd/000000');

insert into room_content (id, content_name, content_url_img) values (49, 'Coat hangers', 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (50, 'Smoke detector', 'http://dummyimage.com/124x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (51, 'Smoke detector', 'http://dummyimage.com/207x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (52, 'Jacuzzi', 'http://dummyimage.com/164x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (53, 'Mini fridge', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (54, 'Pillowcases', 'http://dummyimage.com/232x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (55, 'Microwave', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (56, 'Seating area', 'http://dummyimage.com/232x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (57, 'Lamp', 'http://dummyimage.com/231x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (58, 'Hangers', 'http://dummyimage.com/194x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (59, 'Slippers', 'http://dummyimage.com/188x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (60, 'Alarm clock', 'http://dummyimage.com/163x100.png/dddddd/000000');

insert into room_content (id, content_name, content_url_img) values (61, 'Pillows', 'http://dummyimage.com/164x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (62, 'Napkins', 'http://dummyimage.com/122x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (63, 'Notepad', 'http://dummyimage.com/223x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (64, 'Dining table', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (65, 'Room directory', 'http://dummyimage.com/201x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (66, 'Comforter', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (67, 'Towels', 'http://dummyimage.com/240x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (68, 'Dining table', 'http://dummyimage.com/244x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (69, 'Shower gel', 'http://dummyimage.com/235x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (70, 'Coffee table', 'http://dummyimage.com/246x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (71, 'Luggage storage', 'http://dummyimage.com/169x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (72, 'Dining chairs', 'http://dummyimage.com/237x100.png/cc0000/ffffff');

\! cls
insert into room_content (id, content_name, content_url_img) values (73, 'Safe', 'http://dummyimage.com/161x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (74, 'Conditioner', 'http://dummyimage.com/138x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (75, 'Luggage storage', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (76, 'Comforter', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (77, 'Air conditioning unit', 'http://dummyimage.com/166x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (78, 'Blankets', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (79, 'Wardrobe', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (80, 'Wi-Fi router', 'http://dummyimage.com/157x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (81, 'Safe', 'http://dummyimage.com/122x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (82, 'Rug', 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (83, 'Mirror', 'http://dummyimage.com/209x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (84, 'Napkins', 'http://dummyimage.com/216x100.png/dddddd/000000');

insert into room_content (id, content_name, content_url_img) values (85, 'Dining table', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (86, 'Bath mat', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff');
insert into room_content (id, content_name, content_url_img) values (87, 'Room directory', 'http://dummyimage.com/118x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (88, 'Coffee table', 'http://dummyimage.com/160x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (89, 'Face towels', 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (90, 'Blankets', 'http://dummyimage.com/152x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (91, 'Bathrobe', 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (92, 'Sofas', 'http://dummyimage.com/208x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (93, 'Hairdryer', 'http://dummyimage.com/177x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (94, 'Cups', 'http://dummyimage.com/166x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (95, 'Wall art', 'http://dummyimage.com/205x100.png/ff4444/ffffff');

insert into room_content (id, content_name, content_url_img) values (96, 'Nightstand', 'http://dummyimage.com/242x100.png/ff4444/ffffff');
insert into room_content (id, content_name, content_url_img) values (97, 'Chair', 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (98, 'Dining chairs', 'http://dummyimage.com/199x100.png/dddddd/000000');
insert into room_content (id, content_name, content_url_img) values (99, 'Bath mat', 'http://dummyimage.com/238x100.png/cc0000/ffffff');
insert into room_content (id, content_name, content_url_img) values (100, 'Bottled water', 'http://dummyimage.com/178x100.png/5fa2dd/ffffff');
